//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `Printer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package demo;

public class Response implements java.lang.Cloneable,
                                 java.io.Serializable
{
    public long responseTime;

    public String value;

    public Response()
    {
        this.value = "";
    }

    public Response(long responseTime, String value)
    {
        this.responseTime = responseTime;
        this.value = value;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        Response r = null;
        if(rhs instanceof Response)
        {
            r = (Response)rhs;
        }

        if(r != null)
        {
            if(this.responseTime != r.responseTime)
            {
                return false;
            }
            if(this.value != r.value)
            {
                if(this.value == null || r.value == null || !this.value.equals(r.value))
                {
                    return false;
                }
            }

            return true;
        }

        return false;
    }

    public int hashCode()
    {
        int h_ = 5381;
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, "::Demo::Response");
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, responseTime);
        h_ = com.zeroc.IceInternal.HashUtil.hashAdd(h_, value);
        return h_;
    }

    public Response clone()
    {
        Response c = null;
        try
        {
            c = (Response)super.clone();
        }
        catch(CloneNotSupportedException ex)
        {
            assert false; // impossible
        }
        return c;
    }

    public void ice_writeMembers(com.zeroc.Ice.OutputStream ostr)
    {
        ostr.writeLong(this.responseTime);
        ostr.writeString(this.value);
    }

    public void ice_readMembers(com.zeroc.Ice.InputStream istr)
    {
        this.responseTime = istr.readLong();
        this.value = istr.readString();
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, Response v)
    {
        if(v == null)
        {
            _nullMarshalValue.ice_writeMembers(ostr);
        }
        else
        {
            v.ice_writeMembers(ostr);
        }
    }

    static public Response ice_read(com.zeroc.Ice.InputStream istr)
    {
        Response v = new Response();
        v.ice_readMembers(istr);
        return v;
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, java.util.Optional<Response> v)
    {
        if(v != null && v.isPresent())
        {
            ice_write(ostr, tag, v.get());
        }
    }

    static public void ice_write(com.zeroc.Ice.OutputStream ostr, int tag, Response v)
    {
        if(ostr.writeOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            int pos = ostr.startSize();
            ice_write(ostr, v);
            ostr.endSize(pos);
        }
    }

    static public java.util.Optional<Response> ice_read(com.zeroc.Ice.InputStream istr, int tag)
    {
        if(istr.readOptional(tag, com.zeroc.Ice.OptionalFormat.FSize))
        {
            istr.skip(4);
            return java.util.Optional.of(Response.ice_read(istr));
        }
        else
        {
            return java.util.Optional.empty();
        }
    }

    private static final Response _nullMarshalValue = new Response();

    /** @hidden */
    public static final long serialVersionUID = -5349078849708624650L;
}
